service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  create:
    handler: person/create.create
    events:
  read:
    handler: person/read.read
    events:
  update:
    handler: person/update.update
    events:
  destroy:
    handler: person/destroy.destroy
    events: